[package]
name = "vm"
version = "0.1.0"
edition = "2024"

[lib]
name = "fvm"
path = "src/lib.rs"

[[bin]]
name = "fvm"  # The executable name
path = "src/main.rs"

[dependencies]
serde = { version ="1.0.228", features = ["derive"]  }
serde_json = "1.0.148"
